export const QUERY_COMMENT = 'QUERY_COMMENT';

export const QUERY_COMMENT_BY_ID = 'QUERY_COMMENT_BY_ID';
export const QUERY_CREATE_COMMENT = 'QUERY_CREATE_COMMENT';
export const QUERY_UPDATE_COMMENT = 'QUERY_UPDATE_COMMENT';
export const QUERY_DELETE_COMMENT = 'QUERY_DELETE_COMMENT';
