export const QUERY_ARTICLE = 'QUERY_ARTICLE';

export const QUERY_GET_ALL_ARTICLES = 'QUERY_GET_ALL_ARTICLES';
export const QUERY_GET_ARTICLE_BY_ID = 'QUERY_GET_ARTICLE_BY_ID';
export const QUERY_CREATE_ARTICLE = 'QUERY_CREATE_ARTICLE';
export const QUERY_SEARCH_ARTICLE = 'QUERY_SEARCH_ARTICLE';
export const QUERY_EXPOSE_ARTICLE = 'QUERY_EXPOSE_ARTICLE';
