export const QUERY_PROFILE = 'QUERY_PROFILE';

export const QUERY_GET_PROFILE = 'QUERY_GET_PROFILE';
export const QUERY_UPDATE_PROFILE = 'QUERY_UPDATE_PROFILE';

/**
 * FAQ
 */
export const QUERY_PROFILE_FAQ = 'QUERY_PROFILE_FAQ';
export const QUERY_PROFILE_FAQ_CREATE = 'QUERY_PROFILE_FAQ_CREATE';
export const QUERY_PROFILE_FAQ_UPDATE = 'QUERY_PROFILE_FAQ_UPDATE';
export const QUERY_PROFILE_FAQ_EXPOSE = 'QUERY_PROFILE_FAQ_EXPOSE';
