export const QUERY_CATEGORY = 'QUERY_CATEGORY';

export const QUERY_GET_MAIN_CATEGORYS = 'QUERY_GET_MAIN_CATEGORYS';
export const QUERY_GET_SUB_CATEGORY = 'QUERY_GET_SUB_CATEGORY';
export const QUERY_CREATE_CATEGORY = 'QUERY_CREATE_CATEGORY';
export const QUERY_UPDATE_CATEGORY = 'QUERY_UPDATE_CATEGORY';
